chore: new spacecraft launched by ISRO for the lunar mission, Chandra…
isro/api pull request #52
Opened 2023-08-28 07:44 UTC by Xenofic

…yaan 3

2023-09-01 07:36 UTC, Areeb786123 approved these changes

2023-10-12 18:57 UTC, Taz03 requested changes

2023-10-12 18:57 UTC, Taz03 commented on data/spacecrafts.json
> +            "name": "Chandrayaan3"
```suggestion
            "name": "Chandrayaan-3"
```

2023-10-15 16:48 UTC, Areeb786123 approved these changes
approved

2025-01-03 14:23 UTC, merged